#!/usr/bin/env python3
"""Vendors a deterministic sample of the SingleStepTests/spc700 vector suite (bead grm-c9d.2).

The full suite is ~76 MB uncompressed / ~15 MB packed -- too large to commit next to a repo
whose entire .git is ~22 MB (ruling: vendor a sample, plus an env-var-gated full run against a
separate clone; mirrors the existing gated-synthetic + opt-in-real-ROM split documented in
CLAUDE.md). This script produces that sample: reads a full clone of
https://github.com/SingleStepTests/spc700 and writes the first N cases of each of the 256
per-opcode `v1/<hex>.json` files to `src/test/resources/spc700-vectors/`, plus a MANIFEST.txt
recording provenance so the sample is regenerable and legible.

The suite's cases are already effectively randomly ordered (each file was generated
independently, not sorted by anything meaningful) -- taking a prefix is deliberately NOT
followed by a seeded shuffle, per the grm-c9d.2 bead ruling: a shuffle is one more thing an
agent regenerating this sample later would have to reproduce exactly for a stable diff, for no
benefit over a plain prefix.

Usage:
    python3 tools/spc700/sample-vectors.py --source <full-clone-dir> [--n 32]
        [--dest src/test/resources/spc700-vectors]

The full clone is NOT vendored by this script and is not this repo's job to fetch automatically
(network access during a build is exactly what the sample avoids needing) -- point --source at
a `git clone --depth 1 https://github.com/SingleStepTests/spc700 <dir>` you made yourself,
kept outside the repo.
"""
import argparse
import json
import pathlib
import subprocess
import sys


def git_commit(clone_dir: pathlib.Path) -> str:
    try:
        out = subprocess.run(
            ["git", "-C", str(clone_dir), "rev-parse", "HEAD"],
            check=True, capture_output=True, text=True)
        return out.stdout.strip()
    except Exception as e:  # pragma: no cover - best-effort provenance only
        return f"<unknown: {e}>"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--source", required=True, type=pathlib.Path,
        help="path to a full clone of github.com/SingleStepTests/spc700")
    ap.add_argument("--dest", type=pathlib.Path,
        default=pathlib.Path("src/test/resources/spc700-vectors"),
        help="output directory (default: src/test/resources/spc700-vectors, relative to cwd)")
    ap.add_argument("--n", type=int, default=32,
        help="cases to keep per opcode file (default: 32, i.e. 256 files x 32 = 8192 cases)")
    args = ap.parse_args()

    src_dir = args.source / "v1"
    if not src_dir.is_dir():
        print(f"FAIL: {src_dir} does not exist -- is --source a clone of "
            "SingleStepTests/spc700 (it must contain a v1/ directory)?", file=sys.stderr)
        return 1

    source_files = sorted(src_dir.glob("*.json"))
    if not source_files:
        print(f"FAIL: no *.json files found under {src_dir}", file=sys.stderr)
        return 1

    args.dest.mkdir(parents=True, exist_ok=True)
    commit = git_commit(args.source)
    manifest_lines = [
        "# Generated by tools/spc700/sample-vectors.py -- do not hand-edit.",
        "# Regenerate: python3 tools/spc700/sample-vectors.py --source <full-clone-dir>",
        "#",
        "upstream_repo: https://github.com/SingleStepTests/spc700",
        f"upstream_commit: {commit}",
        f"cases_per_file: {args.n}",
        f"source_pattern: v1/<opcode-hex>.json",
        f"file_count: {len(source_files)}",
    ]

    written = 0
    total_cases = 0
    for src_file in source_files:
        with src_file.open("r", encoding="utf-8") as f:
            cases = json.load(f)
        sample = cases[:args.n]
        dest_file = args.dest / src_file.name
        with dest_file.open("w", encoding="utf-8", newline="\n") as f:
            json.dump(sample, f, indent=1)
            f.write("\n")
        written += 1
        total_cases += len(sample)

    manifest_lines.append(f"total_cases_written: {total_cases}")
    (args.dest / "MANIFEST.txt").write_text("\n".join(manifest_lines) + "\n", encoding="utf-8")

    print(f"wrote {written} files, {total_cases} cases, to {args.dest}")
    print(f"upstream commit: {commit}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
