#!/usr/bin/env python3
"""Generate C64 symbol YAML files for ghidra-retro-machines from mist64/c64ref.

This script reads the fixed-column plain-text reference files from a checkout
of https://github.com/mist64/c64ref (default: D:/git/c64ref) and emits two
symbol YAML files consumed by the ghidra-retro-machines C64 loader/compiler:

  machines/generated/c64ref-kernal.yaml     - KERNAL ROM routine symbols
                                               ($E000-$FFFF), kind: entry/vector
  machines/generated/c64ref-c64mem-zp.yaml  - zero-page variables ($0000-$00FF),
                                               kind: label

Sources chosen (see c64ref/src/*/*.txt headers for column layout):
  - KERNAL:   src/kernal/kernal_prg.txt  (C64 Programmer's Reference Guide,
              English). Other kernal_*.txt files were rejected: kernal_128intern
              and kernal_64intern/kernal_mapc64 etc. are German or C128-focused,
              or otherwise lower quality/incomplete relative to the PRG source.
  - ZEROPAGE: src/c64mem/c64mem_prg.txt (same Programmer's Reference Guide).
              kernal_mapc64/c64mem_mapc64 ("Mapping the Commodore 64") is
              avoided for licensing reasons per project instructions.

Each c64ref text file documents its own fixed-column layout in a `#`-prefixed
header, e.g.:
    # Hex addresses start at column 0.
    # Symbols start at column 7.
    # The description starts at column 15.
This script reads those header lines to find the symbol/description column
offsets rather than hardcoding them, since the two source files use different
column layouts.

Only the first line of each entry's description is kept, as a short
one-line `comment` (matching the "first heading line only" requirement).
Entries with no symbol name are skipped. Address ranges ("$0003-$0004") use
the first address in the range.

The KERNAL/RESET/NMI/IRQ hardware vectors at $FFFA/$FFFC/$FFFE are NOT
documented as data rows in any c64ref kernal source file (they're CPU
vectors, not KERNAL API entries) -- they are added here from well-known,
universally-documented facts about the C64 memory map, not scraped from
c64ref, and are the only entries not derived from the input file.

Usage:
    python3 gen_c64ref_symbols.py [c64ref_dir] [output_dir]

Defaults:
    c64ref_dir = D:/git/c64ref
    output_dir = <repo>/machines/generated  (relative to this script)

The output YAML files are committed to the ghidra-retro-machines repo like
the other hand-authored files under machines/generated/ -- they are
regenerated by re-running this script against a c64ref checkout, not edited
by hand.
"""

import re
import sys
from pathlib import Path

KERNAL_SOURCE = "kernal_prg.txt"
ZP_SOURCE = "c64mem_prg.txt"

KERNAL_MIN = 0xE000
KERNAL_MAX = 0xFFFF
ZP_MIN = 0x0000
ZP_MAX = 0x00FF

# CPU hardware vectors: not present as data rows in any c64ref kernal source
# file, added here from well-known, universally-documented C64 memory map
# facts (not scraped from c64ref).
HARDWARE_VECTORS = [
    (0xFFFA, "NMI", "vector", "NMI interrupt vector"),
    (0xFFFC, "RESET", "vector", "CPU reset vector"),
    (0xFFFE, "IRQ", "vector", "IRQ/BRK interrupt vector"),
]

ADDR_RE = re.compile(r"^\$([0-9A-Fa-f]{1,4})")
SYMCOL_RE = re.compile(r"[Ss]ymbols? start[s]? at column\s+(\d+)", re.IGNORECASE)
DESCCOL_RE = re.compile(r"description starts? at column\s+(\d+)", re.IGNORECASE)


def find_columns(lines):
    """Extract (symbol_col, desc_col) from a c64ref file's '#' header lines."""
    symbol_col = None
    desc_col = None
    for line in lines:
        if not line.startswith("#"):
            continue
        m = SYMCOL_RE.search(line)
        if m:
            symbol_col = int(m.group(1))
        m = DESCCOL_RE.search(line)
        if m:
            desc_col = int(m.group(1))
    if symbol_col is None or desc_col is None:
        raise ValueError("could not find symbol/description column offsets in header")
    return symbol_col, desc_col


def sanitize_name(raw):
    name = raw.strip().upper()
    name = re.sub(r"[^A-Z0-9_]", "_", name)
    if not name:
        return None
    if name[0].isdigit():
        name = "_" + name
    return name


def parse_entries(path, addr_min, addr_max):
    """Parse a c64ref fixed-column text file, yielding (addr, name, comment)."""
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    symbol_col, desc_col = find_columns(lines)

    results = []
    for line in lines:
        if not line.startswith("$"):
            continue  # not a data row (header/separator/comment/blank/continuation)
        m = ADDR_RE.match(line)
        if not m:
            continue
        try:
            addr = int(m.group(1), 16)
        except ValueError:
            continue
        if not (addr_min <= addr <= addr_max):
            continue

        # Symbol and description are pulled by fixed column offset. Guard
        # against short lines (e.g. no description present).
        symbol_field = line[symbol_col:desc_col] if len(line) > symbol_col else ""
        symbol_field = symbol_field.strip()
        if not symbol_field:
            continue  # no symbol name -- skip per spec

        desc_field = line[desc_col:].strip() if len(line) > desc_col else ""
        desc_field = desc_field.replace('"', "'")

        name = sanitize_name(symbol_field)
        if not name:
            continue

        results.append((addr, name, desc_field))
    return results


def dedupe_names(entries):
    """Given a list of (addr, name, kind, comment), suffix duplicate names."""
    seen = {}
    out = []
    for addr, name, kind, comment in entries:
        if name in seen:
            seen[name] += 1
            unique_name = f"{name}_{seen[name]}"
        else:
            seen[name] = 0
            unique_name = name
        out.append((addr, unique_name, kind, comment))
    return out


def write_yaml(path, entries, generator_note):
    lines = [f"# {generator_note}", "entries:"]
    for addr, name, kind, comment in entries:
        parts = [f"addr: 0x{addr:04X}", f"name: {name}", f"kind: {kind}"]
        if comment:
            parts.append(f'comment: "{comment}"')
        lines.append("  - { " + ", ".join(parts) + " }")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main():
    script_dir = Path(__file__).resolve().parent
    c64ref_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("D:/git/c64ref")
    out_dir = (
        Path(sys.argv[2])
        if len(sys.argv) > 2
        else script_dir.parent.parent / "machines" / "generated"
    )
    out_dir.mkdir(parents=True, exist_ok=True)

    note = (
        "generated by tools/gensymbols/gen_c64ref_symbols.py from mist64/c64ref "
        "-- do not hand-edit"
    )

    # --- KERNAL ---
    kernal_path = c64ref_dir / "src" / "kernal" / KERNAL_SOURCE
    kernal_raw = parse_entries(kernal_path, KERNAL_MIN, KERNAL_MAX)
    kernal_entries = [(addr, name, "entry", comment) for addr, name, comment in kernal_raw]
    kernal_entries.extend(HARDWARE_VECTORS)
    kernal_entries.sort(key=lambda e: e[0])
    kernal_entries = dedupe_names(kernal_entries)

    kernal_out = out_dir / "c64ref-kernal.yaml"
    write_yaml(kernal_out, kernal_entries, note)

    # --- Zero page ---
    zp_path = c64ref_dir / "src" / "c64mem" / ZP_SOURCE
    zp_raw = parse_entries(zp_path, ZP_MIN, ZP_MAX)
    zp_entries = [(addr, name, "label", comment) for addr, name, comment in zp_raw]
    zp_entries.sort(key=lambda e: e[0])
    zp_entries = dedupe_names(zp_entries)

    zp_out = out_dir / "c64ref-c64mem-zp.yaml"
    write_yaml(zp_out, zp_entries, note)

    # --- Summary ---
    print(f"KERNAL source:   {kernal_path}")
    print(f"  entries:       {len(kernal_entries)} "
          f"({len(kernal_raw)} parsed + {len(HARDWARE_VECTORS)} hardware vectors)")
    print(f"  written to:    {kernal_out}")
    print()
    print(f"Zero page source: {zp_path}")
    print(f"  entries:       {len(zp_entries)}")
    print(f"  written to:    {zp_out}")


if __name__ == "__main__":
    main()
