/* ###
 * IP: GHIDRA
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package retromachines.vectors;

import static org.junit.Assert.assertTrue;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;

import org.junit.Test;

import ghidra.program.model.lang.Language;

import retromachines.AbstractBundledLanguageTest;

/**
 * Runs the vendored 8192-case NMOS 6502 vector sample
 * ({@code src/test/resources/mos6502-vectors/}, see that directory's {@code MANIFEST.txt} for
 * provenance) through {@link VectorRunner} and checks the per-opcode result against the
 * committed {@code mos6502-vector-baseline.txt}, per the {@link OpcodeBaseline} bless idiom --
 * the NMOS 6502 analogue of {@code Spc700VectorSampleTest} (bead grm-hzv8). Rides in the
 * {@code unit} chunk: ~8000 emulated single instructions, no extension build/install needed.
 *
 * <p>{@code 6502:LE:16:undoc} is BUNDLED by this module (unlike SPC700/W65816, this language has
 * shipped since before this bead), so -- unlike {@code Spc700VectorSampleTest} -- this test does
 * NOT Assume-skip on a missing language; a resolution failure here is a real problem.
 *
 * <p><b>Regenerating the baseline:</b> run with {@code -Dgrm.mos6502.regenerateBaseline=true}
 * (e.g. {@code gradle test -Dgrm.mos6502.regenerateBaseline=true --tests
 * '*Mos6502VectorSampleTest'}). This overwrites
 * {@code src/test/resources/mos6502-vector-baseline.txt} with the current run's results instead
 * of comparing against it -- review the diff, then commit deliberately, exactly like
 * {@code build-and-test.sh bless}.
 */
public class Mos6502VectorSampleTest extends AbstractBundledLanguageTest {

	private static final String REGENERATE_PROPERTY = "grm.mos6502.regenerateBaseline";

	@Test
	public void sampleMatchesCommittedBaseline() throws Exception {
		Language language = Mos6502VectorHarnessSupport.resolveLanguage();

		File moduleRoot = new File(System.getProperty(MODULE_DIR_PROPERTY));
		File vectorsDir = new File(moduleRoot, "src/test/resources/mos6502-vectors");
		List<File> opcodeFiles = Mos6502VectorHarnessSupport.opcodeFilesIn(vectorsDir);
		assertTrue("no vendored vector files found under " + vectorsDir +
			" -- run tools/mos6502/sample-vectors.py", !opcodeFiles.isEmpty());

		VectorRunner runner = Mos6502VectorHarnessSupport.newRunner(language);
		List<OpcodeBaseline> actual = new ArrayList<>();
		for (File f : opcodeFiles) {
			actual.add(Mos6502VectorHarnessSupport.runOpcodeFile(runner, f));
		}
		Mos6502VectorHarnessSupport.assertDecodeBoundaryCapNotExceeded(actual);

		File baselineFile = new File(moduleRoot, "src/test/resources/mos6502-vector-baseline.txt");
		if (Boolean.getBoolean(REGENERATE_PROPERTY)) {
			writeBaseline(baselineFile, actual);
			System.out.println("regenerated " + baselineFile + " (" + actual.size() +
				" opcodes) -- review the diff and commit deliberately");
			return;
		}

		assertTrue("no committed baseline at " + baselineFile + " -- run with -D" +
			REGENERATE_PROPERTY + "=true", baselineFile.isFile());
		List<String> lines = Files.readAllLines(baselineFile.toPath(), StandardCharsets.UTF_8);
		List<OpcodeBaseline> baseline = OpcodeBaseline.parse(lines);

		List<String> problems = OpcodeBaseline.compare(baseline, actual);
		assertTrue("baseline mismatch:\n" + String.join("\n", problems), problems.isEmpty());
	}

	private static void writeBaseline(File file, List<OpcodeBaseline> rows) throws IOException {
		List<String> lines = new ArrayList<>();
		lines.add("# mos6502-vector-baseline.txt -- generated by Mos6502VectorSampleTest with");
		lines.add("# -D" + REGENERATE_PROPERTY + "=true. Review the diff, do not hand-edit");
		lines.add("# casually. See retromachines.vectors.OpcodeBaseline for the file format and");
		lines.add("# retromachines.vectors.Mos6502VectorHarnessSupport for the harness that");
		lines.add("# produced it (vendored sample: src/test/resources/mos6502-vectors/, 32");
		lines.add("# cases/opcode; see that directory's MANIFEST.txt for upstream provenance).");
		lines.add("#");
		lines.add("# Mnemonic column: disassembly of the FIRST vector case's own instruction");
		lines.add("# bytes for that opcode. Operand VALUES are therefore whatever that first");
		lines.add("# case happened to hold -- expected and not a semantic change. Only a changed");
		lines.add("# MNEMONIC or a row that newly falls back to '-' is worth a second look.");
		lines.add("#");
		lines.add("# The packed 'p' field and the hardwired stack-high-byte are adapted into");
		lines.add("# synthetic register-backed fields -- see Mos6502VectorHarnessSupport's class");
		lines.add("# doc for exactly which bits are compared and which are seed-only.");
		lines.addAll(OpcodeBaseline.formatAll(rows));
		Files.write(file.toPath(), lines, StandardCharsets.UTF_8);
	}
}
