/* ###
 * IP: GHIDRA
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package retromachines.vectors;

import static org.junit.Assert.assertTrue;
import static org.junit.Assume.assumeNoException;
import static org.junit.Assume.assumeTrue;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;

import org.junit.Test;

import ghidra.program.model.lang.Language;

import retromachines.AbstractBundledLanguageTest;

/**
 * Runs the vendored 8192-case SPC700 vector sample ({@code src/test/resources/spc700-vectors/},
 * see {@code NOTICE} and that directory's {@code MANIFEST.txt} for provenance) through
 * {@link VectorRunner} and checks the per-opcode result against the committed
 * {@code spc700-vector-baseline.txt}, per the grm-c9d.2 bless-idiom design in
 * {@link OpcodeBaseline}. Rides in the `unit` chunk (bead grm-c9d.2 chunk-registration
 * requirement): ~8000 emulated single instructions, no extension build/install needed.
 *
 * <p><b>Inert until grm-c9d.1 lands.</b> This worktree develops the harness before the SPC700
 * sleigh language is vendored (grm-c9d.1, in parallel) and before any baseline reflecting real
 * SPC700 semantics exists (grm-c9d.3's job) -- both requirements the grm-c9d.2 bead spec states
 * explicitly. Rather than fabricate either, this test Assume-skips (green, not red) when the
 * language or the baseline file is missing, so it activates automatically once both land, with
 * no code change here required.
 *
 * <p><b>Regenerating the baseline:</b> run with {@code -Dgrm.spc700.regenerateBaseline=true}
 * (e.g. {@code gradle test -Dgrm.spc700.regenerateBaseline=true --tests
 * '*Spc700VectorSampleTest'}) once the language exists. This overwrites
 * {@code src/test/resources/spc700-vector-baseline.txt} with the current run's results instead
 * of comparing against it -- review the diff, then commit deliberately, exactly like
 * {@code build-and-test.sh bless}.
 */
public class Spc700VectorSampleTest extends AbstractBundledLanguageTest {

	private static final String REGENERATE_PROPERTY = "grm.spc700.regenerateBaseline";

	@Test
	public void sampleMatchesCommittedBaseline() throws Exception {
		Language language;
		try {
			language = Spc700VectorHarnessSupport.resolveLanguage();
		}
		catch (Exception e) {
			assumeNoException("SPC700 language (" + Spc700VectorHarnessSupport.LANGUAGE_ID +
				") is not available in this worktree -- expected until grm-c9d.1 lands; " +
				"this test activates automatically once it does", e);
			return;
		}

		File moduleRoot = new File(System.getProperty(MODULE_DIR_PROPERTY));
		File vectorsDir = new File(moduleRoot, "src/test/resources/spc700-vectors");
		List<File> opcodeFiles = Spc700VectorHarnessSupport.opcodeFilesIn(vectorsDir);
		assertTrue("no vendored vector files found under " + vectorsDir +
			" -- run tools/spc700/sample-vectors.py", !opcodeFiles.isEmpty());

		VectorRunner runner = Spc700VectorHarnessSupport.newRunner(language);
		List<OpcodeBaseline> actual = new ArrayList<>();
		for (File f : opcodeFiles) {
			actual.add(Spc700VectorHarnessSupport.runOpcodeFile(runner, f));
		}
		Spc700VectorHarnessSupport.assertDecodeBoundaryCapNotExceeded(actual);

		File baselineFile = new File(moduleRoot, "src/test/resources/spc700-vector-baseline.txt");
		if (Boolean.getBoolean(REGENERATE_PROPERTY)) {
			writeBaseline(baselineFile, actual);
			System.out.println("regenerated " + baselineFile + " (" + actual.size() +
				" opcodes) -- review the diff and commit deliberately");
			return;
		}

		if (!baselineFile.isFile()) {
			assumeTrue("no committed baseline at " + baselineFile + " yet (grm-c9d.3's job); " +
				"regenerate with -D" + REGENERATE_PROPERTY + "=true once the language exists",
				false);
			return;
		}
		List<String> lines = Files.readAllLines(baselineFile.toPath(), StandardCharsets.UTF_8);
		List<OpcodeBaseline> baseline = OpcodeBaseline.parse(lines);

		List<String> problems = OpcodeBaseline.compare(baseline, actual);
		assertTrue("baseline mismatch:\n" + String.join("\n", problems), problems.isEmpty());
	}

	private static void writeBaseline(File file, List<OpcodeBaseline> rows) throws IOException {
		List<String> lines = new ArrayList<>();
		lines.add("# spc700-vector-baseline.txt -- generated by Spc700VectorSampleTest with");
		lines.add("# -D" + REGENERATE_PROPERTY + "=true. Review the diff, do not hand-edit");
		lines.add("# casually. See retromachines.vectors.OpcodeBaseline for the file format and");
		lines.add("# retromachines.vectors.Spc700VectorHarnessSupport for the harness that");
		lines.add("# produced it (vendored sample: src/test/resources/spc700-vectors/, 32");
		lines.add("# cases/opcode; see that directory's MANIFEST.txt for upstream provenance).");
		lines.add("#");
		lines.add("# Mnemonic column: disassembly of the FIRST vector case's own instruction");
		lines.add("# bytes for that opcode. Operand VALUES are therefore whatever that first");
		lines.add("# case happened to hold (e.g. 'MOV A,0x10' vs 'MOV A,0x7f' on a re-run) --");
		lines.add("# expected and not a semantic change. Only a changed MNEMONIC or a row that");
		lines.add("# newly falls back to '-' is worth a second look.");
		lines.addAll(OpcodeBaseline.formatAll(rows));
		Files.write(file.toPath(), lines, StandardCharsets.UTF_8);
	}
}
