/* ###
 * IP: GHIDRA
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Verifies C64BankingAnalyzer behavior on the banktest/banktest2 regression PRGs
// (generated by mkbanktest.py; driven by run-banktest.sh).
//
// Dumps a normalized behavior report between "=== BANKDUMP BEGIN ===" and
// "=== BANKDUMP END ===" markers (EOL comments containing "bank ->", bookmarks in
// the C64BankingAnalyzer category, and instruction references into overlay
// spaces), then evaluates per-program criteria, printing one
// "CRITERION <id> PASS|FAIL <detail>" line each and "SUITE PASS" only when all
// criteria passed. Detects which test program it is running against by whether
// the program name contains "banktest2".
//@category RetroMachines.Test

import java.util.ArrayList;
import java.util.Collections;
import java.util.Iterator;
import java.util.List;

import ghidra.app.script.GhidraScript;
import ghidra.program.model.address.Address;
import ghidra.program.model.address.AddressSpace;
import ghidra.program.model.listing.Bookmark;
import ghidra.program.model.listing.CommentType;
import ghidra.program.model.listing.Instruction;
import ghidra.program.model.listing.InstructionIterator;
import ghidra.program.model.symbol.Reference;

public class VerifyBankTest extends GhidraScript {

	private static final String CATEGORY = "C64BankingAnalyzer";

	private boolean allPassed = true;

	@Override
	protected void run() throws Exception {
		dump();

		String name = currentProgram.getName();
		if (name.contains("banktest4")) {
			checkBanktest4();
		}
		else if (name.contains("banktest3")) {
			checkBanktest3();
		}
		else if (name.contains("banktest2")) {
			checkBanktest2();
		}
		else {
			checkBanktest();
		}

		println(allPassed ? "SUITE PASS" : "SUITE FAIL");
	}

	// ------------------------------------------------------------------
	// Normalized behavior dump
	// ------------------------------------------------------------------

	private void dump() {
		List<String> comments = new ArrayList<>();
		List<String> bookmarks = new ArrayList<>();
		List<String> refs = new ArrayList<>();

		InstructionIterator instrs = currentProgram.getListing().getInstructions(true);
		while (instrs.hasNext()) {
			Instruction instr = instrs.next();
			Address at = instr.getMinAddress();

			String eol = currentProgram.getListing().getComment(CommentType.EOL, at);
			if (eol != null && eol.contains("bank ->")) {
				comments.add("COMMENT " + fmt(at) + " " + eol);
			}

			for (Reference r : instr.getReferencesFrom()) {
				AddressSpace toSpace = r.getToAddress().getAddressSpace();
				if (toSpace.isOverlaySpace()) {
					refs.add("REF " + fmt(at) + " -> " + toSpace.getName() + "::" +
						fmt(r.getToAddress()) + " " + r.getReferenceType().getName() +
						" primary=" + r.isPrimary());
				}
			}
		}

		Iterator<Bookmark> bms = currentProgram.getBookmarkManager().getBookmarksIterator();
		while (bms.hasNext()) {
			Bookmark bm = bms.next();
			if (CATEGORY.equals(bm.getCategory())) {
				bookmarks.add("BOOKMARK " + bm.getTypeString() + " " + fmt(bm.getAddress()));
			}
		}

		Collections.sort(comments);
		Collections.sort(bookmarks);
		Collections.sort(refs);

		println("=== BANKDUMP BEGIN ===");
		for (String line : comments) {
			println(line);
		}
		for (String line : bookmarks) {
			println(line);
		}
		for (String line : refs) {
			println(line);
		}
		println("=== BANKDUMP END ===");
	}

	// ------------------------------------------------------------------
	// banktest.prg criteria (basic overlay retargeting)
	// ------------------------------------------------------------------

	private void checkBanktest() {
		// C1: LDA $A000 in state 5 -> overlay READ ref RAM_A000::a000, primary
		Reference r = findOverlayRef(0x080F, "RAM_A000", 0xA000);
		criterion("C1", r != null && r.getReferenceType().isRead() && r.isPrimary(),
			"read of $A000 in bank 5 retargeted to RAM_A000 overlay, primary: " + describe(r));

		// C2: STA $E000 in state 5 -> overlay WRITE ref RAM_E000::e000
		r = findOverlayRef(0x0812, "RAM_E000", 0xE000);
		criterion("C2", r != null && r.getReferenceType().isWrite(),
			"write of $E000 in bank 5 retargeted to RAM_E000 overlay: " + describe(r));

		// C3: STA $A000 in home state 7 -> write-under-ROM overlay WRITE ref, primary
		r = findOverlayRef(0x0805, "RAM_A000", 0xA000);
		criterion("C3", r != null && r.getReferenceType().isWrite() && r.isPrimary(),
			"write under BASIC ROM in bank 7 retargeted to RAM_A000 overlay, primary: " +
				describe(r));

		// C4: JSR $FFD2 in state 7 -> KERNAL is home, no overlay ref from this instruction
		criterion("C4", overlayRefCount(0x0808) == 0,
			"JSR $FFD2 in bank 7 left untouched (" + overlayRefCount(0x0808) +
				" overlay refs)");

		// C5/C6: fully-known bank-switch comments at the two STA $01 sites
		String c = eol(0x0803);
		criterion("C5", c.contains("bank -> 7 (") && !c.contains("?"),
			"fully known bank -> 7 comment at 0803: \"" + c + "\"");
		c = eol(0x080D);
		criterion("C6", c.contains("bank -> 5 (") && !c.contains("?"),
			"fully known bank -> 5 comment at 080d: \"" + c + "\"");
	}

	// ------------------------------------------------------------------
	// banktest2.prg criteria (masked-RMW, partial knowledge, warnings, merge)
	// ------------------------------------------------------------------

	private void checkBanktest2() {
		// C1: LDA $01 / AND #$FE / STA $01 with in-state 5 resolves exactly to bank 4
		String c = eol(0x0809);
		criterion("C1", c.contains("bank -> 4 (") && !c.contains("?"),
			"in-state fallback resolves AND #$FE exactly at 0809: \"" + c + "\"");

		// C2: LDA $01 / AND #$F8 / ORA #$05 / STA $01 resolves by mask algebra alone
		c = eol(0x0811);
		criterion("C2", c.contains("bank -> 5 (") && !c.contains("?"),
			"mask algebra alone resolves bank 5 at 0811: \"" + c + "\"");

		// C3: LDA $0400 / STA $01 is undeterminable -> WARNING bookmark, no comment
		criterion("C3", hasWarningBookmark(0x0816) && !eol(0x0816).contains("bank ->"),
			"undeterminable store at 0816: warning=" + hasWarningBookmark(0x0816) +
				" comment=\"" + eol(0x0816) + "\"");

		// C4: LDA $01 / ORA #$04 / STA $01 with unknown in-state -> partial (CHAREN known)
		c = eol(0x081C);
		criterion("C4",
			c.contains("bank -> 7? (") &&
				c.contains("[known: CHAREN=1; assumed from initial: LORAM,HIRAM]") &&
				!hasWarningBookmark(0x081C),
			"partial-knowledge comment, no warning, at 081c: \"" + c + "\"");

		// C5: LDA #$35 / JSR sub / STA $01 -> call clobbers the immediate -> WARNING
		criterion("C5", hasWarningBookmark(0x0823),
			"call-clobber store at 0823: warning=" + hasWarningBookmark(0x0823));

		// C6: backward scan from the STA at 082d crosses the intervening STX $01, so the
		// base must NOT inherit in-state (which would yield fully-known "bank -> 6 (");
		// only the ORA #$02 bit (HIRAM) is known, the rest is assumed from initial.
		c = eol(0x082D);
		criterion("C6",
			c.contains("? (") && c.contains("[known: HIRAM=1;") && !c.contains("bank -> 6 ("),
			"crossing-mechanism-write abort yields partial comment at 082d: \"" + c + "\"");

		// C7: merge of states 5 and 4 keeps agreeing bits (HIRAM=0, CHAREN=1); effective
		// state 5 -> the LDA $A000 at the join gets an overlay READ ref
		Reference r = findOverlayRef(0x083F, "RAM_A000", 0xA000);
		criterion("C7", r != null && r.getReferenceType().isRead(),
			"join-point read of $A000 retargeted to RAM_A000 overlay: " + describe(r));
	}

	// ------------------------------------------------------------------
	// banktest3.prg criteria (the two P1 value-recovery fixes)
	// ------------------------------------------------------------------

	private void checkBanktest3() {
		// B1 (grm-5tl.1): the JSR at 0805 calls a helper that takes its bank argument in
		// X (STX $01). The caller loads an unrelated immediate into A (LDA #$AA -> bank 2)
		// and the real bank into X (LDX #$34 -> bank 4). The recovered bank must come from
		// the register the helper actually reads (X = 4), not the old A-first guess (2).
		String c = eol(0x0805);
		criterion("B1",
			c.contains("bank -> 4 (") && c.contains("via") && !c.contains("bank -> 2"),
			"helper call recovers X argument (bank 4), not A (bank 2), at 0805: \"" + c + "\"");

		// A1 (grm-5tl.2): the STA $01 at 080F is a branch-join target -- reached by
		// fall-through from LDA #$36 (A=$36) and by the BEQ at 080B (A undetermined). The
		// backward value scan must not confidently fold $36 at the join; the store is
		// ambiguous -> WARNING bookmark, no "bank ->" comment.
		criterion("A1",
			hasWarningBookmark(0x080F) && !eol(0x080F).contains("bank ->"),
			"join-target store is ambiguous at 080f: warning=" + hasWarningBookmark(0x080F) +
				" comment=\"" + eol(0x080F) + "\"");
	}

	// ------------------------------------------------------------------
	// banktest4.prg criteria (READ_WRITE reference split, bead grm-5tl.16)
	// ------------------------------------------------------------------

	private void checkBanktest4() {
		// D1: INC $A000 in home state 7 is a read-modify-write across the write-under-ROM
		// boundary: it reads BASIC (the LOROM home occupant in state 7) and writes RAM_A000
		// (BASIC's on_write target, not home). The write side must get a primary WRITE
		// overlay ref to RAM_A000; the pre-fix bug pointed the *whole* RMW (including the
		// read) at the write target via a single overlay ref.
		Reference w = findOverlayRef(0x0805, "RAM_A000", 0xA000);
		criterion("D1", w != null && w.getReferenceType().isWrite() && w.isPrimary(),
			"INC $A000 in bank 7 gets a primary WRITE overlay ref to RAM_A000: " + describe(w));

		// D2: the read side must NOT be redirected to RAM_A000 (or any overlay space) --
		// BASIC is the home occupant for LOROM in state 7, so the read is already correctly
		// resolved by the original base-space reference and needs no overlay ref. A READ
		// overlay ref to RAM_A000 here is exactly the pre-fix misdirection bug.
		Reference readOverlay = null;
		Instruction instr = currentProgram.getListing().getInstructionAt(addr(0x0805));
		if (instr != null) {
			for (Reference r : instr.getReferencesFrom()) {
				if (r.getReferenceType().isRead() && r.getToAddress().getAddressSpace().isOverlaySpace()) {
					readOverlay = r;
					break;
				}
			}
		}
		criterion("D2", readOverlay == null,
			"no READ overlay ref at 0805 (read resolves via base-space ref to home BASIC): " +
				describe(readOverlay));

		// D3: exactly one overlay reference total from this instruction -- the primary WRITE
		// ref -- confirming the read side was left alone rather than also redirected.
		criterion("D3", overlayRefCount(0x0805) == 1,
			"exactly one overlay ref (the WRITE) at 0805 (" + overlayRefCount(0x0805) +
				" found)");
	}

	// ------------------------------------------------------------------
	// Helpers
	// ------------------------------------------------------------------

	private void criterion(String id, boolean passed, String detail) {
		if (!passed) {
			allPassed = false;
		}
		println("CRITERION " + id + " " + (passed ? "PASS" : "FAIL") + " " + detail);
	}

	private Address addr(long offset) {
		return currentProgram.getAddressFactory().getDefaultAddressSpace().getAddress(offset);
	}

	private static String fmt(Address a) {
		return String.format("%04x", a.getOffset());
	}

	private String eol(long offset) {
		String c = currentProgram.getListing().getComment(CommentType.EOL, addr(offset));
		return c == null ? "" : c;
	}

	private boolean hasWarningBookmark(long offset) {
		for (Bookmark bm : currentProgram.getBookmarkManager().getBookmarks(addr(offset))) {
			if (CATEGORY.equals(bm.getCategory()) && "Warning".equals(bm.getTypeString())) {
				return true;
			}
		}
		return false;
	}

	private Reference findOverlayRef(long from, String spaceName, long toOffset) {
		Instruction instr = currentProgram.getListing().getInstructionAt(addr(from));
		if (instr == null) {
			return null;
		}
		for (Reference r : instr.getReferencesFrom()) {
			AddressSpace toSpace = r.getToAddress().getAddressSpace();
			if (toSpace.isOverlaySpace() && toSpace.getName().equals(spaceName) &&
				r.getToAddress().getOffset() == toOffset) {
				return r;
			}
		}
		return null;
	}

	private int overlayRefCount(long from) {
		Instruction instr = currentProgram.getListing().getInstructionAt(addr(from));
		if (instr == null) {
			return 0;
		}
		int count = 0;
		for (Reference r : instr.getReferencesFrom()) {
			if (r.getToAddress().getAddressSpace().isOverlaySpace()) {
				count++;
			}
		}
		return count;
	}

	private static String describe(Reference r) {
		if (r == null) {
			return "<no matching overlay reference>";
		}
		return r.getToAddress().getAddressSpace().getName() + "::" + fmt(r.getToAddress()) +
			" " + r.getReferenceType().getName() + " primary=" + r.isPrimary();
	}
}
