/* ###
 * IP: GHIDRA
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Verifies C64BankingAnalyzer and NesBankingAnalyzer behavior on the banktest*
// regression PRGs (C64, generated by mkbanktest.py) and the nesbanktest ROM (NES,
// generated by mknesbanktest.py; driven by run-banktest.sh).
//
// Dumps a normalized behavior report between "=== BANKDUMP BEGIN ===" and
// "=== BANKDUMP END ===" markers (memory blocks with their overlay-ness, EOL
// comments containing "bank ->", bookmarks in the *BankingAnalyzer category, and
// instruction references into overlay spaces), then evaluates per-program
// criteria, printing one "CRITERION <id> PASS|FAIL <detail>" line each and
// "SUITE PASS" only when all criteria passed. Detects which test program it is
// running against by the program name.
//@category RetroMachines.Test

import java.util.ArrayList;
import java.util.Collections;
import java.util.Iterator;
import java.util.List;

import ghidra.app.script.GhidraScript;
import ghidra.program.model.address.Address;
import ghidra.program.model.address.AddressSpace;
import ghidra.program.model.listing.Bookmark;
import ghidra.program.model.listing.CommentType;
import ghidra.program.model.listing.Instruction;
import ghidra.program.model.listing.InstructionIterator;
import ghidra.program.model.mem.MemoryBlock;
import ghidra.program.model.symbol.Reference;

public class VerifyBankTest extends GhidraScript {

	// Each BoardBankAnalyzer subclass bookmarks under its own class-name category
	// (BoardBankAnalyzer.getBookmarkCategory() default); the C64 and NES fixtures never
	// run in the same program, but the dump/lookup helpers below accept either so one
	// script covers both suites.
	private static final String CATEGORY_C64 = "C64BankingAnalyzer";
	private static final String CATEGORY_NES = "NesBankingAnalyzer";

	private boolean allPassed = true;

	@Override
	protected void run() throws Exception {
		dump();

		String name = currentProgram.getName();
		if (name.contains("nesmmc1test")) {
			checkNesMmc1test();
		}
		else if (name.contains("nesserialtest")) {
			checkNesSerialtest();
		}
		else if (name.contains("nesmmc3test")) {
			checkNesMmc3test();
		}
		else if (name.contains("nesmodetest")) {
			checkNesModetest();
		}
		else if (name.contains("nesbanktest2")) {
			checkNesBanktest2();
		}
		else if (name.contains("nesbanktest")) {
			checkNesBanktest();
		}
		else if (name.contains("banktest4")) {
			checkBanktest4();
		}
		else if (name.contains("banktest3")) {
			checkBanktest3();
		}
		else if (name.contains("banktest2")) {
			checkBanktest2();
		}
		else {
			checkBanktest();
		}

		println(allPassed ? "SUITE PASS" : "SUITE FAIL");
	}

	// ------------------------------------------------------------------
	// Normalized behavior dump
	// ------------------------------------------------------------------

	private void dump() {
		List<String> blocks = new ArrayList<>();
		List<String> comments = new ArrayList<>();
		List<String> bookmarks = new ArrayList<>();
		List<String> refs = new ArrayList<>();

		// Load-time memory layout (bead grm-5tl.17): locks block names, ranges, and
		// overlay-ness as a regression net for the loader refactor tracked by grm-5tl.14.
		for (MemoryBlock block : currentProgram.getMemory().getBlocks()) {
			blocks.add("BLOCK " + block.getName() + " " + fmt(block.getStart()) + "-" +
				fmt(block.getEnd()) + " overlay=" + block.isOverlay());
		}

		InstructionIterator instrs = currentProgram.getListing().getInstructions(true);
		while (instrs.hasNext()) {
			Instruction instr = instrs.next();
			Address at = instr.getMinAddress();

			String eol = currentProgram.getListing().getComment(CommentType.EOL, at);
			if (eol != null && eol.contains("bank ->")) {
				comments.add("COMMENT " + fmt(at) + " " + eol);
			}

			for (Reference r : instr.getReferencesFrom()) {
				AddressSpace toSpace = r.getToAddress().getAddressSpace();
				if (toSpace.isOverlaySpace()) {
					refs.add("REF " + fmt(at) + " -> " + toSpace.getName() + "::" +
						fmt(r.getToAddress()) + " " + r.getReferenceType().getName() +
						" primary=" + r.isPrimary());
				}
			}
		}

		Iterator<Bookmark> bms = currentProgram.getBookmarkManager().getBookmarksIterator();
		while (bms.hasNext()) {
			Bookmark bm = bms.next();
			if (CATEGORY_C64.equals(bm.getCategory()) || CATEGORY_NES.equals(bm.getCategory())) {
				bookmarks.add("BOOKMARK " + bm.getTypeString() + " " + fmt(bm.getAddress()));
			}
		}

		Collections.sort(blocks);
		Collections.sort(comments);
		Collections.sort(bookmarks);
		Collections.sort(refs);

		println("=== BANKDUMP BEGIN ===");
		for (String line : blocks) {
			println(line);
		}
		for (String line : comments) {
			println(line);
		}
		for (String line : bookmarks) {
			println(line);
		}
		for (String line : refs) {
			println(line);
		}
		println("=== BANKDUMP END ===");
	}

	// ------------------------------------------------------------------
	// banktest.prg criteria (basic overlay retargeting)
	// ------------------------------------------------------------------

	private void checkBanktest() {
		// C1: LDA $A000 in state 5 -> overlay READ ref RAM_A000::a000, primary
		Reference r = findOverlayRef(0x080F, "RAM_A000", 0xA000);
		criterion("C1", r != null && r.getReferenceType().isRead() && r.isPrimary(),
			"read of $A000 in bank 5 retargeted to RAM_A000 overlay, primary: " + describe(r));

		// C2: STA $E000 in state 5 -> overlay WRITE ref RAM_E000::e000
		r = findOverlayRef(0x0812, "RAM_E000", 0xE000);
		criterion("C2", r != null && r.getReferenceType().isWrite(),
			"write of $E000 in bank 5 retargeted to RAM_E000 overlay: " + describe(r));

		// C3: STA $A000 in home state 7 -> write-under-ROM overlay WRITE ref, primary
		r = findOverlayRef(0x0805, "RAM_A000", 0xA000);
		criterion("C3", r != null && r.getReferenceType().isWrite() && r.isPrimary(),
			"write under BASIC ROM in bank 7 retargeted to RAM_A000 overlay, primary: " +
				describe(r));

		// C4: JSR $FFD2 in state 7 -> KERNAL is home, no overlay ref from this instruction
		criterion("C4", overlayRefCount(0x0808) == 0,
			"JSR $FFD2 in bank 7 left untouched (" + overlayRefCount(0x0808) +
				" overlay refs)");

		// C5/C6: fully-known bank-switch comments at the two STA $01 sites
		String c = eol(0x0803);
		criterion("C5", c.contains("bank -> 7 (") && !c.contains("?"),
			"fully known bank -> 7 comment at 0803: \"" + c + "\"");
		c = eol(0x080D);
		criterion("C6", c.contains("bank -> 5 (") && !c.contains("?"),
			"fully known bank -> 5 comment at 080d: \"" + c + "\"");
	}

	// ------------------------------------------------------------------
	// banktest2.prg criteria (masked-RMW, partial knowledge, warnings, merge)
	// ------------------------------------------------------------------

	private void checkBanktest2() {
		// C1: LDA $01 / AND #$FE / STA $01 with in-state 5 resolves exactly to bank 4
		String c = eol(0x0809);
		criterion("C1", c.contains("bank -> 4 (") && !c.contains("?"),
			"in-state fallback resolves AND #$FE exactly at 0809: \"" + c + "\"");

		// C2: LDA $01 / AND #$F8 / ORA #$05 / STA $01 resolves by mask algebra alone
		c = eol(0x0811);
		criterion("C2", c.contains("bank -> 5 (") && !c.contains("?"),
			"mask algebra alone resolves bank 5 at 0811: \"" + c + "\"");

		// C3: LDA $0400 / STA $01 is undeterminable -> WARNING bookmark, no comment
		criterion("C3", hasWarningBookmark(0x0816) && !eol(0x0816).contains("bank ->"),
			"undeterminable store at 0816: warning=" + hasWarningBookmark(0x0816) +
				" comment=\"" + eol(0x0816) + "\"");

		// C4: LDA $01 / ORA #$04 / STA $01 with unknown in-state -> partial (CHAREN known)
		c = eol(0x081C);
		criterion("C4",
			c.contains("bank -> 7? (") &&
				c.contains("[known: CHAREN=1; assumed from initial: LORAM,HIRAM]") &&
				!hasWarningBookmark(0x081C),
			"partial-knowledge comment, no warning, at 081c: \"" + c + "\"");

		// C5: LDA #$35 / JSR sub / STA $01 -> call clobbers the immediate -> WARNING
		criterion("C5", hasWarningBookmark(0x0823),
			"call-clobber store at 0823: warning=" + hasWarningBookmark(0x0823));

		// C6: backward scan from the STA at 082d crosses the intervening STX $01, so the
		// base must NOT inherit in-state (which would yield fully-known "bank -> 6 (");
		// only the ORA #$02 bit (HIRAM) is known, the rest is assumed from initial.
		c = eol(0x082D);
		criterion("C6",
			c.contains("? (") && c.contains("[known: HIRAM=1;") && !c.contains("bank -> 6 ("),
			"crossing-mechanism-write abort yields partial comment at 082d: \"" + c + "\"");

		// C7: merge of states 5 and 4 keeps agreeing bits (HIRAM=0, CHAREN=1); effective
		// state 5 -> the LDA $A000 at the join gets an overlay READ ref
		Reference r = findOverlayRef(0x083F, "RAM_A000", 0xA000);
		criterion("C7", r != null && r.getReferenceType().isRead(),
			"join-point read of $A000 retargeted to RAM_A000 overlay: " + describe(r));
	}

	// ------------------------------------------------------------------
	// banktest3.prg criteria (the two P1 value-recovery fixes)
	// ------------------------------------------------------------------

	private void checkBanktest3() {
		// B1 (grm-5tl.1): the JSR at 0805 calls a helper that takes its bank argument in
		// X (STX $01). The caller loads an unrelated immediate into A (LDA #$AA -> bank 2)
		// and the real bank into X (LDX #$34 -> bank 4). The recovered bank must come from
		// the register the helper actually reads (X = 4), not the old A-first guess (2).
		String c = eol(0x0805);
		criterion("B1",
			c.contains("bank -> 4 (") && c.contains("via") && !c.contains("bank -> 2"),
			"helper call recovers X argument (bank 4), not A (bank 2), at 0805: \"" + c + "\"");

		// A1 (grm-5tl.2): the STA $01 at 080F is a branch-join target -- reached by
		// fall-through from LDA #$36 (A=$36) and by the BEQ at 080B (A undetermined). The
		// backward value scan must not confidently fold $36 at the join; the store is
		// ambiguous -> WARNING bookmark, no "bank ->" comment.
		criterion("A1",
			hasWarningBookmark(0x080F) && !eol(0x080F).contains("bank ->"),
			"join-target store is ambiguous at 080f: warning=" + hasWarningBookmark(0x080F) +
				" comment=\"" + eol(0x080F) + "\"");
	}

	// ------------------------------------------------------------------
	// banktest4.prg criteria (READ_WRITE reference split, bead grm-5tl.16)
	// ------------------------------------------------------------------

	private void checkBanktest4() {
		// D1: INC $A000 in home state 7 is a read-modify-write across the write-under-ROM
		// boundary: it reads BASIC (the LOROM home occupant in state 7) and writes RAM_A000
		// (BASIC's on_write target, not home). The write side must get a primary WRITE
		// overlay ref to RAM_A000; the pre-fix bug pointed the *whole* RMW (including the
		// read) at the write target via a single overlay ref.
		Reference w = findOverlayRef(0x0805, "RAM_A000", 0xA000);
		criterion("D1", w != null && w.getReferenceType().isWrite() && w.isPrimary(),
			"INC $A000 in bank 7 gets a primary WRITE overlay ref to RAM_A000: " + describe(w));

		// D2: the read side must NOT be redirected to RAM_A000 (or any overlay space) --
		// BASIC is the home occupant for LOROM in state 7, so the read is already correctly
		// resolved by the original base-space reference and needs no overlay ref. A READ
		// overlay ref to RAM_A000 here is exactly the pre-fix misdirection bug.
		Reference readOverlay = null;
		Instruction instr = currentProgram.getListing().getInstructionAt(addr(0x0805));
		if (instr != null) {
			for (Reference r : instr.getReferencesFrom()) {
				if (r.getReferenceType().isRead() && r.getToAddress().getAddressSpace().isOverlaySpace()) {
					readOverlay = r;
					break;
				}
			}
		}
		criterion("D2", readOverlay == null,
			"no READ overlay ref at 0805 (read resolves via base-space ref to home BASIC): " +
				describe(readOverlay));

		// D3: exactly one overlay reference total from this instruction -- the primary WRITE
		// ref -- confirming the read side was left alone rather than also redirected.
		criterion("D3", overlayRefCount(0x0805) == 1,
			"exactly one overlay ref (the WRITE) at 0805 (" + overlayRefCount(0x0805) +
				" found)");
	}

	// ------------------------------------------------------------------
	// nesbanktest.nes criteria (NesRomLoader + NesBankingAnalyzer, bead grm-5tl.17)
	// ------------------------------------------------------------------

	private void checkNesBanktest() {
		// N1: the fixed window (PRG_HI) and the switchable window's home bank (PRG_LO,
		// un-suffixed -- bank 0 is the home/initial state) both land as base-space blocks.
		MemoryBlock prgHi = currentProgram.getMemory().getBlock("PRG_HI");
		criterion("N1a", prgHi != null && !prgHi.isOverlay(),
			"PRG_HI fixed block exists in base space: " + describeBlock(prgHi));
		MemoryBlock prgLo = currentProgram.getMemory().getBlock("PRG_LO");
		criterion("N1b", prgLo != null && !prgLo.isOverlay(),
			"PRG_LO home-bank block exists un-suffixed in base space: " + describeBlock(prgLo));

		// N2: every non-home bank (1, 2, 3 -- the fixture's PRG has 4 x 16 KiB banks) gets
		// an overlay block named <window>_B<bank>.
		MemoryBlock b1 = currentProgram.getMemory().getBlock("PRG_LO_B1");
		MemoryBlock b2 = currentProgram.getMemory().getBlock("PRG_LO_B2");
		MemoryBlock b3 = currentProgram.getMemory().getBlock("PRG_LO_B3");
		criterion("N2", b1 != null && b1.isOverlay() && b2 != null && b2.isOverlay() &&
			b3 != null && b3.isOverlay(),
			"PRG_LO_B1/_B2/_B3 overlay blocks exist: " + describeBlock(b1) + ", " +
				describeBlock(b2) + ", " + describeBlock(b3));

		// N3: empirical no-mangling check -- each overlay block's AddressSpace name equals
		// the block name (no Ghidra-side suffixing/renaming of the overlay space).
		for (MemoryBlock b : new MemoryBlock[] { b1, b2, b3 }) {
			if (b == null) {
				continue;
			}
			String blockName = b.getName();
			String spaceName = b.getStart().getAddressSpace().getName();
			criterion("N3:" + blockName, spaceName.equals(blockName),
				"overlay space name equals block name: block=\"" + blockName + "\" space=\"" +
					spaceName + "\"");
		}

		// N4: the mapper-latch write (LDA #$02 / STA $FFF0) at $C002 gets a fully-known
		// "bank -> 2" comment -- exercises MemoryLatchBankSwitchStrategy's bus-conflict path
		// (the STA's target $FFF0 is a bank-invariant ROM byte this fixture set to 0x02, so
		// the AND is a faithful no-op on the driven value).
		String c = eol(0xC002);
		criterion("N4", c.contains("bank -> 2 (") && !c.contains("?"),
			"fully known bank -> 2 comment at c002: \"" + c + "\"");

		// N5: the JSR $8005 at $C005, taken with bank=2 in effect (non-home -- PRG_LO's
		// home bank is 0), retargets into the PRG_LO_B2 overlay space.
		Reference r = findOverlayRef(0xC005, "PRG_LO_B2", 0x8005);
		criterion("N5", r != null && r.getReferenceType().isCall() && r.isPrimary(),
			"JSR $8005 in bank 2 retargeted to PRG_LO_B2 overlay, primary: " + describe(r));
	}

	// ------------------------------------------------------------------
	// nesbanktest2.nes criteria (3-deep overlay-bank JSR chain, bead grm-5tl.13.3)
	// ------------------------------------------------------------------

	private void checkNesBanktest2() {
		// F1: RESET's JSR $8005 at $C005, taken with bank=2 in effect, retargets into the
		// PRG_LO_B2 overlay space -- round 1 evidence.
		Reference r = findOverlayRef(0xC005, "PRG_LO_B2", 0x8005);
		criterion("F1", r != null && r.getReferenceType().isCall() && r.isPrimary(),
			"JSR $8005 in bank 2 retargeted to PRG_LO_B2 overlay, primary: " + describe(r));

		// F2: trampoline1's JSR $8010 at $C015 retargets into PRG_LO_B1 -- this instruction
		// is only disassembled at all once round 1's flow-follow from PRG_LO_B2::8005's own
		// JSR $C010 reaches it, and is only analyzed in round 2, so a resolved ref here is
		// round-2 evidence.
		r = findOverlayRef(0xC015, "PRG_LO_B1", 0x8010);
		criterion("F2", r != null && r.getReferenceType().isCall() && r.isPrimary(),
			"JSR $8010 in bank 1 (trampoline1, round-2 evidence) retargeted to PRG_LO_B1 " +
				"overlay, primary: " + describe(r));

		// F3: trampoline2's JSR $8030 at $C025 retargets into PRG_LO_B3 -- reachable only
		// through trampoline1's JSR $C020, itself only disassembled by round 2's flow-follow
		// and only analyzed in round 3. This is the deepest reference in the chain, and its
		// resolution is direct proof that at least 3 full analyzer rounds ran to convergence
		// -- the load-bearing criterion for bead grm-5tl.13.3's fingerprint-skip guard.
		r = findOverlayRef(0xC025, "PRG_LO_B3", 0x8030);
		criterion("F3", r != null && r.getReferenceType().isCall() && r.isPrimary(),
			"JSR $8030 in bank 3 (trampoline2, round-3/deepest evidence -- proves >= 3 " +
				"analyzer rounds converged) retargeted to PRG_LO_B3 overlay, primary: " +
				describe(r));

		// F4: fully-known bank-switch comments at the five latch-write sites (the two
		// forward selects at c002/c012/c022, and the two restores at c01a/c02a).
		String c = eol(0xC002);
		criterion("F4:c002", c.contains("bank -> 2 (") && !c.contains("?"),
			"fully known bank -> 2 comment at c002: \"" + c + "\"");
		c = eol(0xC012);
		criterion("F4:c012", c.contains("bank -> 1 (") && !c.contains("?"),
			"fully known bank -> 1 comment at c012: \"" + c + "\"");
		c = eol(0xC022);
		criterion("F4:c022", c.contains("bank -> 3 (") && !c.contains("?"),
			"fully known bank -> 3 comment at c022: \"" + c + "\"");
		c = eol(0xC01A);
		criterion("F4:c01a", c.contains("bank -> 2 (") && !c.contains("?"),
			"fully known bank -> 2 (restore) comment at c01a: \"" + c + "\"");
		c = eol(0xC02A);
		criterion("F4:c02a", c.contains("bank -> 1 (") && !c.contains("?"),
			"fully known bank -> 1 (restore) comment at c02a: \"" + c + "\"");

		// F5: the phase-2 disassembly cascade actually produced instructions at all three
		// deepest overlay targets -- without this, F1-F3's refs couldn't exist, but this
		// checks the disassembly (not just the reference) landed where expected.
		criterion("F5:PRG_LO_B2_8005", hasInstructionAt("PRG_LO_B2", 0x8005),
			"instruction exists at PRG_LO_B2::8005");
		criterion("F5:PRG_LO_B1_8010", hasInstructionAt("PRG_LO_B1", 0x8010),
			"instruction exists at PRG_LO_B1::8010");
		criterion("F5:PRG_LO_B3_8030", hasInstructionAt("PRG_LO_B3", 0x8030),
			"instruction exists at PRG_LO_B3::8030");
	}

	// ------------------------------------------------------------------
	// nesmodetest.nes criteria (memory.layouts[] mode-varying windows, bead grm-qvi)
	// ------------------------------------------------------------------

	private void checkNesModetest() {
		// F1: RESET's JSR $8000 at $C005, taken with bank=1 in effect (mode still 0/home),
		// retargets into the home layout's non-home-bank overlay W8000_M0_B1.
		Reference r = findOverlayRef(0xC005, "W8000_M0_B1", 0x8000);
		criterion("F1", r != null && r.getReferenceType().isCall() && r.isPrimary(),
			"JSR $8000 (mode0/bank1) retargeted to W8000_M0_B1 overlay, primary: " + describe(r));

		// F2: RESET's JMP $8040 at $C00D, taken after the mode latch write (prg_mode -> 1),
		// retargets into the mode-1 FIXED instance of W8000 (W8000_M1) -- proves the mode
		// field alone (no bank field) drives a fixed-window instance's retargeting. The
		// reference type is CALL, not JUMP: the W8000_M1 routine's only exit is its own
		// self-loop (JMP $8048, never RTS), so Ghidra's stock non-returning-function
		// analysis marks FUN_W8000_M1__8040 non-returning and reclassifies this tail-JMP
		// as a call terminator -- a default Ghidra behavior orthogonal to bank retargeting,
		// evidenced by the "via FUN_W8000_M1__8040" wording this also adds to c00d's
		// bank-switch comment (see the F4 checks below, which do not depend on it).
		r = findOverlayRef(0xC00D, "W8000_M1", 0x8040);
		criterion("F2", r != null && r.getReferenceType().isCall() && r.isPrimary(),
			"JMP $8040 (mode1) retargeted to W8000_M1 overlay (as a CALL -- Ghidra's " +
				"non-returning-function reclassification), primary: " + describe(r));

		// F3: the JSR $C030 at (overlay-relative) 8045 -- physically inside the W8000_M1
		// overlay -- retargets into WC000_M1_B2. This is the load-bearing criterion: mode=1
		// is known only because clampToResidence pins it from the instruction's own overlay
		// (W8000_M1 exists only under prg_mode=1), and bank=2 comes from the latch write at
		// 8042 inside that same overlay; the two-level mode -> window -> bank lookup then
		// finds WC000's mode-1 switchable instance at bank 2. Structurally impossible before
		// residence-clamping understood mode-qualified overlays.
		r = findOverlayRefFrom(overlayAddr("W8000_M1", 0x8045), "WC000_M1_B2", 0xC030);
		criterion("F3", r != null && r.getReferenceType().isCall() && r.isPrimary(),
			"JSR $C030 in W8000_M1 (mode1/bank2) retargeted to WC000_M1_B2 overlay, primary: " +
				describe(r));

		// F4: bank-switch comments at the three latch-write sites. Each write is recognized
		// by a mechanism that owns only ONE of the two state fields (bank / prg_mode), so
		// per the multi-mechanism engine's per-switch-effect annotation these are partial
		// comments: the acted-on field is "known", the other field falls back to "assumed
		// from initial" -- assert on the effective per-field breakdown, not exact wording.
		String c = eol(0xC002);
		criterion("F4:c002", c.contains("bank -> 1") && c.contains("bank=1") &&
			c.contains("known: bank"),
			"bank latch -> 1 (bank field known, prg_mode assumed) at c002: \"" + c + "\"");
		c = eol(0xC00A);
		criterion("F4:c00a", c.contains("prg_mode=1") && c.contains("known: prg_mode"),
			"mode latch -> 1 (prg_mode field known, bank assumed) at c00a: \"" + c + "\"");
		c = eol("W8000_M1", 0x8042);
		criterion("F4:8042", c.contains("bank -> 2") && c.contains("bank=2") &&
			c.contains("known: bank"),
			"bank latch -> 2 inside overlay (bank field known, prg_mode assumed) at 8042: \"" +
				c + "\"");

		// F5: the phase-2 disassembly cascade actually produced instructions at all three
		// overlay targets reached above.
		criterion("F5:W8000_M0_B1_8000", hasInstructionAt("W8000_M0_B1", 0x8000),
			"instruction exists at W8000_M0_B1::8000");
		criterion("F5:W8000_M1_8040", hasInstructionAt("W8000_M1", 0x8040),
			"instruction exists at W8000_M1::8040");
		criterion("F5:WC000_M1_B2_C030", hasInstructionAt("WC000_M1_B2", 0xC030),
			"instruction exists at WC000_M1_B2::C030");
	}

	// ------------------------------------------------------------------
	// nesmmc3test.nes criteria (SelectDataBankSwitchStrategy, bead grm-6a7.1)
	// ------------------------------------------------------------------

	private void checkNesMmc3test() {
		// F1: RESET's JSR $8000 at $E00A, with r6=2/prg_mode=0 in effect (just latched by
		// the select=6/data=2 write pair), retargets into the mode-0 switchable instance's
		// non-home-bank overlay W8000_M0_B2.
		Reference r = findOverlayRef(0xE00A, "W8000_M0_B2", 0x8000);
		criterion("F1", r != null && r.getReferenceType().isCall() && r.isPrimary(),
			"JSR $8000 (mode0/r6=2) retargeted to W8000_M0_B2 overlay, primary: " + describe(r));

		// F2: RESET's second JSR $8000 at $E017 -- issued AFTER a select=0 (CHR)/data=$AA
		// write pair in between -- retargets to the SAME W8000_M0_B2 overlay, proving r6
		// SURVIVED the CHR write (SelectDataBankSwitchStrategy's no-poison contract).
		r = findOverlayRef(0xE017, "W8000_M0_B2", 0x8000);
		criterion("F2", r != null && r.getReferenceType().isCall() && r.isPrimary(),
			"JSR $8000 after a CHR-register write still retargets to W8000_M0_B2 (r6 " +
				"survived the CHR write, no-poison contract holds): " + describe(r));

		// F3: RESET's JSR $A000 at $E024, with r7=3 in effect, retargets into WA000_B3 --
		// WA000 is INVARIANT-HOISTED (identical across both prg_mode layouts), so the
		// overlay name carries no _M qualifier at all.
		r = findOverlayRef(0xE024, "WA000_B3", 0xA000);
		criterion("F3", r != null && r.getReferenceType().isCall() && r.isPrimary(),
			"JSR $A000 (r7=3) retargeted to hoisted WA000_B3 overlay (no _M qualifier), " +
				"primary: " + describe(r));

		// F4: RESET's JSR $C000 at $E02C, issued AFTER the mode-flip write (select=6,
		// prg_mode=1, co-emitted from ONE byte), retargets into WC000's mode-1 switchable
		// instance at the still-known r6=2 -- proves the mode bit and the select index
		// were correctly split out of the same recovered byte, and that r6 survived every
		// intervening write (including the CHR write at $E014).
		r = findOverlayRef(0xE02C, "WC000_M1_B2", 0xC000);
		criterion("F4", r != null && r.getReferenceType().isCall() && r.isPrimary(),
			"JSR $C000 after the mode flip (prg_mode=1, r6=2) retargeted to WC000_M1_B2 " +
				"overlay, primary: " + describe(r));

		// F5: bank-switch comments exist at the mechanism write sites -- the two select
		// writes that flip prg_mode (home 0 stays known throughout, then the flip to 1)
		// and the two data writes that set r6/r7.
		String c = eol(0xE002);
		criterion("F5:e002", c.contains("bank ->"),
			"bank-switch comment at the select=6 write (e002): \"" + c + "\"");
		c = eol(0xE007);
		criterion("F5:e007", c.contains("bank ->"),
			"bank-switch comment at the r6=2 data write (e007): \"" + c + "\"");
		c = eol(0xE021);
		criterion("F5:e021", c.contains("bank ->"),
			"bank-switch comment at the r7=3 data write (e021): \"" + c + "\"");
		c = eol(0xE029);
		criterion("F5:e029", c.contains("bank ->") && c.contains("prg_mode=1"),
			"bank-switch comment at the mode-flip select write (e029) shows prg_mode=1: \"" +
				c + "\"");

		// F6: the phase-2 disassembly cascade actually produced instructions at all three
		// overlay targets reached above (the dual-mapped bank-2 RTS routine, referenced from
		// two different overlay names, plus the bank-3 routine).
		criterion("F6:W8000_M0_B2_8000", hasInstructionAt("W8000_M0_B2", 0x8000),
			"instruction exists at W8000_M0_B2::8000");
		criterion("F6:WC000_M1_B2_C000", hasInstructionAt("WC000_M1_B2", 0xC000),
			"instruction exists at WC000_M1_B2::C000");
		criterion("F6:WA000_B3_A000", hasInstructionAt("WA000_B3", 0xA000),
			"instruction exists at WA000_B3::A000");
	}

	// ------------------------------------------------------------------
	// nesserialtest.nes criteria (SerialShiftBankSwitchStrategy, bead grm-hsv.1)
	// ------------------------------------------------------------------

	private void checkNesSerialtest() {
		// F-reset: the bit-7-set write at $C002 (LDA #$80 / STA $8000) forces prg_mode=3
		// known -- idempotent re-assertion of the seeded initial state (this board's home
		// mode already is prg_mode=3), but the comment must show it as known, not "?".
		String c = eol(0xC002);
		criterion("F-reset", c.contains("prg_mode=3") && !c.contains("?"),
			"bit-7 reset -> prg_mode=3 known at c002: \"" + c + "\"");

		// F-unrolled: the 5th write of the canonical-address ($E000) chain at $C017
		// commits prg_bank=5; the JSR $8000 right after it at $C01A retargets into the
		// mode-3 (this board's home mode), non-home-bank overlay W8000_M3_B5.
		c = eol(0xC017);
		criterion("F-unrolled:comment", c.contains("prg_bank=5"),
			"unrolled chain commits prg_bank=5 at c017: \"" + c + "\"");
		Reference r = findOverlayRef(0xC01A, "W8000_M3_B5", 0x8000);
		criterion("F-unrolled:jsr", r != null && r.getReferenceType().isCall() && r.isPrimary(),
			"JSR $8000 (prg_bank=5) retargeted to W8000_M3_B5 overlay, primary: " +
				describe(r));

		// Writes 1-4 of the unrolled chain (c007-c013) are no-change echoes: inState flows
		// through UNCHANGED (still the seeded prg_bank=0), never the eventual prg_bank=5 --
		// the commit is deferred entirely to write 5 (c017, checked above).
		c = eol(0xC007);
		criterion("F-unrolled:echo-not-early-commit", c.contains("prg_bank=0"),
			"write 1 of the chain (c007) echoes the still-unchanged prg_bank=0, not an " +
				"early commit: \"" + c + "\"");

		// F-noncanonical: the 5th write of the $FFF9 chain (same 8K window as $E000,
		// bits 14:13 both decode to target 3/PRG) at $C02F commits prg_bank=6 via a
		// non-canonical address -- FF1's exact trick ($9FFF/$BFFF/$DFFF/$FFF9). The JSR
		// $8000 at $C032 retargets into W8000_M3_B6.
		c = eol(0xC02F);
		criterion("F-noncanonical:comment", c.contains("prg_bank=6"),
			"non-canonical-address chain commits prg_bank=6 at c02f: \"" + c + "\"");
		r = findOverlayRef(0xC032, "W8000_M3_B6", 0x8000);
		criterion("F-noncanonical:jsr", r != null && r.getReferenceType().isCall() && r.isPrimary(),
			"JSR $8000 (prg_bank=6, non-canonical commit) retargeted to W8000_M3_B6 " +
				"overlay, primary: " + describe(r));

		// F-chr-discard: the chain to $A000 (CHR0, target 1 -- no `targets` entry in the
		// board's serial-shift mechanism) is recognized but discarded: prg_bank must
		// SURVIVE untouched, proven by the JSR $8000 at $C04A still retargeting to
		// W8000_M3_B6 (bank 6, set by F-noncanonical above, not clobbered by the CHR
		// write in between).
		r = findOverlayRef(0xC04A, "W8000_M3_B6", 0x8000);
		criterion("F-chr-discard", r != null && r.getReferenceType().isCall() && r.isPrimary(),
			"JSR $8000 after a CHR0 chain still retargets to W8000_M3_B6 (prg_bank " +
				"survived the discarded CHR commit): " + describe(r));

		// F-loop: the counted-loop idiom (LDA #$03 / LDY #$05 / loop: STA $E000 / LSR A /
		// DEY / BNE loop). The commit attaches to the BNE at $C056 (the secondary
		// recognizer claims the branch in computeSwitch -- no engine hook; see
		// SerialShiftBankSwitchStrategy's javadoc), fully known since every field was
		// known coming in.
		c = eol(0xC056);
		criterion("F-loop:comment", c.contains("prg_bank=3") && !c.contains("?"),
			"counted loop commits prg_bank=3 at its BNE (c056): \"" + c + "\"");

		// The in-loop STA at $C051 must be suppressed (echo, not poison): no WARNING
		// bookmark, and no CONFIDENT early commit of prg_bank=3. Its comment is the
		// honest MERGE of its two predecessors -- the loop entry (pre-loop prg_bank=6)
		// and the BNE's back edge (which carries the committed prg_bank=3, by design --
		// see SerialShiftBankSwitchStrategy's javadoc on the back-edge flow) -- so the
		// agreeing bits stay known and the disagreeing prg_bank bits degrade to "?",
		// exactly what BankState.merge produces at any other join.
		c = eol(0xC051);
		criterion("F-loop:body-suppressed",
			!hasWarningBookmark(0xC051) && !(c.contains("prg_bank=3") && !c.contains("?")),
			"in-loop STA (c051) suppressed -- no warning, no confident early commit " +
				"(merge of pre-loop 6 and back-edge 3): warning=" +
				hasWarningBookmark(0xC051) + " comment=\"" + c + "\"");

		// The JSR $8000 on the loop's exit edge at $C058 retargets into W8000_M3_B3.
		r = findOverlayRef(0xC058, "W8000_M3_B3", 0x8000);
		criterion("F-loop:jsr", r != null && r.getReferenceType().isCall() && r.isPrimary(),
			"JSR $8000 after the counted loop (prg_bank=3) retargeted to W8000_M3_B3 " +
				"overlay, primary: " + describe(r));

		// F-unresolvable: write 1 of the chain seeded from an opaque indexed load
		// (LDX #$00 / LDA $C200,X) at $C060 can't have its own bit 7 resolved -> honest
		// poison -> WARNING bookmark, no false "bank ->" claim. The chain's 5th write
		// (c070) also degrades (target known from the address, value unresolvable) --
		// neither site may claim a definite bank value.
		criterion("F-unresolvable:write1",
			hasWarningBookmark(0xC060) && !eol(0xC060).contains("bank ->"),
			"unresolvable chain seed warns, no false comment, at c060: warning=" +
				hasWarningBookmark(0xC060) + " comment=\"" + eol(0xC060) + "\"");
		criterion("F-unresolvable:commit", !eol(0xC070).contains("prg_bank=6") &&
			!eol(0xC070).contains("prg_bank=5") && !eol(0xC070).contains("prg_bank=3"),
			"unresolvable chain's commit at c070 makes no false prg_bank claim: \"" +
				eol(0xC070) + "\"");

		// F-partial-bit7: an isolated (non-chained) write to $8000 whose stored value is
		// unresolvable (LDX #$01 / LDA $C200,X / STA $8000, no preceding/following
		// LSR/STA) at $C078 -- bit 7 unknown must poison, and critically must NOT be
		// misclassified as a confident reset (no false prg_mode=3 claim).
		criterion("F-partial-bit7",
			hasWarningBookmark(0xC078) && !eol(0xC078).contains("prg_mode=3"),
			"unresolvable isolated write warns, no false reset claim, at c078: warning=" +
				hasWarningBookmark(0xC078) + " comment=\"" + eol(0xC078) + "\"");

		// Disassembly sanity: the three JSR-target overlay instructions actually exist.
		criterion("F5:W8000_M3_B3_8000", hasInstructionAt("W8000_M3_B3", 0x8000),
			"instruction exists at W8000_M3_B3::8000");
		criterion("F5:W8000_M3_B5_8000", hasInstructionAt("W8000_M3_B5", 0x8000),
			"instruction exists at W8000_M3_B5::8000");
		criterion("F5:W8000_M3_B6_8000", hasInstructionAt("W8000_M3_B6", 0x8000),
			"instruction exists at W8000_M3_B6::8000");
	}

	// ------------------------------------------------------------------
	// nesmmc1test.nes criteria (REAL machines/nes-mmc1.yaml board, bead grm-hsv.2)
	// ------------------------------------------------------------------
	//
	// DESIGN NOTE (bug found by this fixture, since fixed): helper call-site argument
	// recovery (BoardBankAnalyzer.recoverCallArgument) originally positioned the
	// recovered register value with the MECHANISM-wide (effectMask, lsb) -- correct only
	// for single-field mechanisms (register-write, memory-latch), wrong for serial-shift,
	// whose ONE mechanism spans multiple disjoint targets (mirroring+prg_mode via target
	// 0, prg_bank via target 3): LDA #$02 / JSR SwitchBank deposited 2 at the window's
	// bit 0 (mirroring=2) instead of through prg_bank's field list. The fix gives the
	// STRATEGY ownership of the deposit: BankSwitchStrategy.depositHelperArgument
	// (default = historical verbatim-byte behavior, owning the whole field-local width)
	// takes the helper's own recognized switch-site instruction -- HelperModel now
	// carries the matched strategy and that site's address -- and SerialShift's override
	// decodes the site's target (write-5 STA address bits 14:13, or a counted loop's STA
	// via the BNE matcher) and deposits only through that target's TargetField list,
	// returning an ownedMask so unowned sibling fields are left untouched (not poisoned;
	// a CHR-target site owns nothing and the call is treated as a verified no-op).
	// Helper-call EOL comments render from the mechanism-window post-call state (in-state
	// echo narrowed to the helper's effectMask, like a direct computeSwitch result), while
	// the WARNING decision still keys off the call's own recovered effect -- M9's honest
	// warning is unchanged.

	private void checkNesMmc1test() {
		// Addresses per tools/banktest/mknesbanktest.py's make_prg_mmc1() label dump:
		// switch_bank=$C200, mode2_target=$C300, reset=$C000, f_reset=$C002,
		// call1_imm=$C005, call1_jsr=$C007, call1_use_jsr=$C00A, chr_commit=$C01F,
		// call2_imm=$C022, call2_jsr=$C024, call2_use_jsr=$C027, call3_imm=$C02A,
		// call3_jsr=$C02C, mode_commit=$C041, mode2_jsr=$C044, unresolvable_load=$C049,
		// unresolvable_jsr=$C04C, idle=$C04F, rti=$C052.

		// M1: the reset dance (LDA #$80 / STA $8000) at $C002 forces prg_mode=3 known --
		// idempotent re-assertion of the seeded home mode, comment must show it known.
		String c = eol(0xC002);
		criterion("M1", c.contains("prg_mode=3") && !c.contains("?"),
			"reset dance -> prg_mode=3 known at c002: \"" + c + "\"");

		// M2: call site 1's JSR $C200 (SwitchBank) at $C007 -- the LOAD-BEARING check for
		// this bead: findHelpers/recoverCallArgument must recognize $C200 as a bank-switch
		// helper function (argReg='A', recovered from the helper's own chain-write-1
		// register) and resolve THIS call's argument via a backward scan from the JSR
		// itself (LDA #$02 immediately precedes it) -- fully known, no "?", carrying a
		// "via <helper>" annotation (same shape as banktest3's B1 criterion).
		c = eol(0xC007);
		criterion("M2", c.contains("bank -> ") && c.contains("prg_bank=2") &&
			!c.contains("?") && c.contains("via"),
			"helper call site 1 resolves prg_bank=2 via SwitchBank, no '?', at c007: \"" +
				c + "\"");

		// M3: the JSR $8000 right after it, at $C00A, retargets to W8000_M3_B2 (mode 3 is
		// this board's home mode; bank 2 is non-home -> the _M3_B2 overlay).
		Reference r = findOverlayRef(0xC00A, "W8000_M3_B2", 0x8000);
		criterion("M3", r != null && r.getReferenceType().isCall() && r.isPrimary(),
			"JSR $8000 (prg_bank=2) retargeted to W8000_M3_B2 overlay, primary: " +
				describe(r));

		// M4: call site 2's JSR $C200 at $C024 -- issued AFTER the CHR0 chain to $A000
		// (target 1, no `targets` entry) sandwiched between the two PRG switches --
		// resolves prg_bank=5 via the SAME helper, proving prg_bank survived the
		// discarded CHR write (SerialShiftBankSwitchStrategy's no-poison contract).
		c = eol(0xC024);
		criterion("M4", c.contains("bank -> ") && c.contains("prg_bank=5") &&
			!c.contains("?") && c.contains("via"),
			"helper call site 2 resolves prg_bank=5 via SwitchBank (survived the CHR " +
				"chain), no '?', at c024: \"" + c + "\"");

		// M5: the JSR $8000 after it, at $C027, retargets to W8000_M3_B5.
		r = findOverlayRef(0xC027, "W8000_M3_B5", 0x8000);
		criterion("M5", r != null && r.getReferenceType().isCall() && r.isPrimary(),
			"JSR $8000 (prg_bank=5) retargeted to W8000_M3_B5 overlay, primary: " +
				describe(r));

		// M6: call site 3's JSR $C200 at $C02C resolves prg_bank=7 via the same helper --
		// this is the commit that stages prg_bank=7 for the mode-2 transition below (bank
		// 7 == `last`, matching WC000's fixed-last home content, so the transition doesn't
		// move the ground out from under the running code -- see the fixture's module
		// doc). Unlike M2/M5 there is no follow-up JSR $8000 (bank 7 IS this running
		// code, not a separate routine).
		c = eol(0xC02C);
		criterion("M6", c.contains("bank -> ") && c.contains("prg_bank=7") &&
			!c.contains("?") && c.contains("via"),
			"helper call site 3 resolves prg_bank=7 via SwitchBank, no '?', at c02c: \"" +
				c + "\"");

		// M7: the mode-2 transition chain's commit (5th write of the inline Control chain
		// to $8000) at $C041 shows prg_mode=2 (fix-first) fully known -- mirroring stays
		// 0, prg_bank stays 7 (survived every write above), so the WHOLE state is known,
		// no '?'.
		c = eol(0xC041);
		criterion("M7", c.contains("prg_mode=2") && !c.contains("?"),
			"mode-2 transition commits prg_mode=2, fully known, at c041: \"" + c + "\"");

		// M8: the JSR $C300 right after the transition, at $C044, retargets to
		// WC000_M2_B7 -- WC000 just became the switchable window (mode 2), at the
		// current prg_bank=7; this is the "post-switch control flow survives" check: the
		// JSR instruction itself sits in the SAME physical bytes (bank 7) before and
		// after the flip, only the symbolic window name changes.
		r = findOverlayRef(0xC044, "WC000_M2_B7", 0xC300);
		criterion("M8", r != null && r.getReferenceType().isCall() && r.isPrimary(),
			"JSR $C300 after the mode-2 transition retargeted to WC000_M2_B7 overlay, " +
				"primary: " + describe(r));

		// M9: call site 4's JSR $C200 at $C04C -- an opaque indexed load (LDX #$00 / LDA
		// $C400,X) feeds the same helper's argReg='A'; recoverCallArgument's backward
		// scan cannot resolve an indexed load (same limitation nesserialtest's
		// F-unresolvable exercises for an inline chain's seed) -> honest WARNING
		// bookmark at the JSR itself, no false "bank ->" claim. This is the Metroid-
		// mailbox analog for the HELPER call-site value-recovery path specifically.
		criterion("M9", hasWarningBookmark(0xC04C) && !eol(0xC04C).contains("bank ->"),
			"unresolvable helper call warns, no false comment, at c04c: warning=" +
				hasWarningBookmark(0xC04C) + " comment=\"" + eol(0xC04C) + "\"");

		// M10: disassembly sanity -- the JSR-target overlay instructions actually exist.
		criterion("M10:W8000_M3_B2_8000", hasInstructionAt("W8000_M3_B2", 0x8000),
			"instruction exists at W8000_M3_B2::8000");
		criterion("M10:W8000_M3_B5_8000", hasInstructionAt("W8000_M3_B5", 0x8000),
			"instruction exists at W8000_M3_B5::8000");
		criterion("M10:WC000_M2_B7_C300", hasInstructionAt("WC000_M2_B7", 0xC300),
			"instruction exists at WC000_M2_B7::C300");
	}

	private static String describeBlock(MemoryBlock b) {
		if (b == null) {
			return "<missing>";
		}
		return b.getName() + " " + fmt(b.getStart()) + "-" + fmt(b.getEnd()) + " overlay=" +
			b.isOverlay();
	}

	// ------------------------------------------------------------------
	// Helpers
	// ------------------------------------------------------------------

	private void criterion(String id, boolean passed, String detail) {
		if (!passed) {
			allPassed = false;
		}
		println("CRITERION " + id + " " + (passed ? "PASS" : "FAIL") + " " + detail);
	}

	private Address addr(long offset) {
		return currentProgram.getAddressFactory().getDefaultAddressSpace().getAddress(offset);
	}

	private static String fmt(Address a) {
		return String.format("%04x", a.getOffset());
	}

	private String eol(long offset) {
		String c = currentProgram.getListing().getComment(CommentType.EOL, addr(offset));
		return c == null ? "" : c;
	}

	/** Overlay-space address, or the base-space address if {@code spaceName} does not
	 *  resolve (lets callers fail with a null-instruction criterion rather than an NPE). */
	private Address overlayAddr(String spaceName, long offset) {
		AddressSpace space = currentProgram.getAddressFactory().getAddressSpace(spaceName);
		return space == null ? addr(offset) : space.getAddress(offset);
	}

	/** {@link #eol(long)}, but for an instruction physically located in an overlay space
	 *  (e.g. a mode-qualified overlay -- {@code memory.layouts[]} instances, bead grm-qvi). */
	private String eol(String spaceName, long offset) {
		String c = currentProgram.getListing().getComment(CommentType.EOL,
			overlayAddr(spaceName, offset));
		return c == null ? "" : c;
	}

	private boolean hasWarningBookmark(long offset) {
		for (Bookmark bm : currentProgram.getBookmarkManager().getBookmarks(addr(offset))) {
			boolean ourCategory = CATEGORY_C64.equals(bm.getCategory()) ||
				CATEGORY_NES.equals(bm.getCategory());
			if (ourCategory && "Warning".equals(bm.getTypeString())) {
				return true;
			}
		}
		return false;
	}

	private Reference findOverlayRef(long from, String spaceName, long toOffset) {
		return findOverlayRefFrom(addr(from), spaceName, toOffset);
	}

	/** {@link #findOverlayRef}, but for an instruction physically located in an overlay
	 *  space (see {@link #overlayAddr}) rather than base space. */
	private Reference findOverlayRefFrom(Address from, String spaceName, long toOffset) {
		Instruction instr = currentProgram.getListing().getInstructionAt(from);
		if (instr == null) {
			return null;
		}
		for (Reference r : instr.getReferencesFrom()) {
			AddressSpace toSpace = r.getToAddress().getAddressSpace();
			if (toSpace.isOverlaySpace() && toSpace.getName().equals(spaceName) &&
				r.getToAddress().getOffset() == toOffset) {
				return r;
			}
		}
		return null;
	}

	private boolean hasInstructionAt(String spaceName, long offset) {
		AddressSpace space = currentProgram.getAddressFactory().getAddressSpace(spaceName);
		if (space == null) {
			return false;
		}
		return currentProgram.getListing().getInstructionAt(space.getAddress(offset)) != null;
	}

	private int overlayRefCount(long from) {
		Instruction instr = currentProgram.getListing().getInstructionAt(addr(from));
		if (instr == null) {
			return 0;
		}
		int count = 0;
		for (Reference r : instr.getReferencesFrom()) {
			if (r.getToAddress().getAddressSpace().isOverlaySpace()) {
				count++;
			}
		}
		return count;
	}

	private static String describe(Reference r) {
		if (r == null) {
			return "<no matching overlay reference>";
		}
		return r.getToAddress().getAddressSpace().getName() + "::" + fmt(r.getToAddress()) +
			" " + r.getReferenceType().getName() + " primary=" + r.isPrimary();
	}
}
